spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/상권분석
    username: root
    password: 2saekiyaanj!
    driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          default_batch_fetch_size: 1000
          dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
      database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
      database: mysql

    mvc:
      path match:
        matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug